# Welcome, 2015-16 MLab Team!

September 23, 2015

<p>This academic year, the MLab team will continue working on the <a href="http://maker.uvic.ca/kch">Kits for Cultural History</a> while attending conferences, teaching at <a href="http://dhsi.org/" target="_blank">DHSI 2016</a>, facilitating local workshops and talks, and collaborating with <a href="http://williamjturkel.net/" target="_blank">William J. Turkel</a>, <a href="http://devonelliott.net/" target="_blank">Devon Elliott</a>, and other researchers at Western. I&#8217;m very happy to announce that <a href="http://maker.uvic.ca/author/kat/">Katherine Goertz</a> and <a href="http://maker.uvic.ca/author/danielle/">Danielle Morgan</a>&#8212;both of whom were with the Lab last year&#8212;are continuing with the team during 2015-16. Joining us are Teddie Brock, Tiffany Chan, Liam Cline, Victoria Murawski, and Nadia Timperio.</p>
<p>Teddie is in her fourth year of the Bachelor of Arts program in English Literature. Her academic interests include cultural and media studies, as well as experimental traditions in film and literature.</p>
<p><a href="http://thisistiffanychan.com/" target="_blank">Tiffany</a> is starting her first year as an MA student in English, with a specialization in Nineteenth Century Studies. One of her major projects last year (at Queen&#8217;s University) was <a href="http://library.queensu.ca/virtual-exhibits/stereoscopic/" target="_blank">a virtual exhibit of stereoscopic (3D) photography</a>. Outside of that, she has compiled <a href="http://slides.com/tiffchan/hdtmt/#/">a very informative sample of undergraduate digital humanities projects</a> and made <a href="http://thisistiffanychan.com/2015/06/19/reimagining-in-a-station-of-the-metro-as-an-animated-gif/">an animated GIF of a famous Ezra Pound poem</a>. She is also a <a href="https://www.hastac.org/u/tiffany-chan" target="_blank">2015-16 HASTAC Scholar</a>.</p>
<p>Liam is nearing the finale of his electrical engineering BEng program at UVic and is fascinated by &#8220;light-bending&#8221;: creating visual art using electronics and lighting. Last year, he designed the electronics and lighting for <em>The Mushroom</em>, a ten-foot-tall piece that incorporated 1200 multicolour lights to create an interactive glowing environment. <em>The Mushroom</em> served as the centerpiece display for the afterparty of TEDx Victoria 2014. Following graduation in December, Liam intends to pursue light-bending full time, focusing on making stage pieces for musicians.</p>
<p>Victoria is currently entering her final year of the Master of Fine Arts program at UVic. Her art practice is sculpture-based and through this she explores perception and the dissolving subject/object dichotomy. She is currently writing about traditional forms of object fabrication and new(er) digital fabrication processes to investigate the social and political implications of fixed form vs. material contingency.</p>
<p>Nadia is a second-year MA student in the English department. Her research interests lie in questions of cultural representation and identity construction in American literature. She is presently working to complete her Master&#8217;s essay, which examines the translation of narration from the page to stage in several dramatic adaptations of Richard Wright&#8217;s <em>Native Son</em>.</p>
<p>Welcome to the 2015-16 team, Teddie, Tiffany, Liam, Kat, Danielle, Victoria, and Nadia! Looking forward.</p>
<hr />
<p>Post by <a title="learn more" href="http://maker.uvic.ca/author/admin/">Jentery Sayers</a>, attached to the <a title="learn more" href="http://maker.uvic.ca/category/makerspace/">Makerspace</a> project, with the <a title="learn more" href="http://maker.uvic.ca/tag/news/">news</a> tag. Featured image for this post care of Jentery Sayers.</p>
